service: capstone-api

plugins:
  - serverless-offline
  # - serverless-layers

provider:
  name: aws
  region: us-east-2
  stage: dev
  runtime: nodejs20.x

functions:
  main:
    timeout: 30
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
