service: capstone-api

plugins:
  - serverless-offline
  # - serverless-layers

provider:
  name: aws
  region: us-east-2
  stage: dev
  runtime: nodejs20.x

deploymentBucket:
  name: serverless-framework-deployments-us-east-2-58f98f42-79b4

functions:
  main:
    timeout: 29
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
